import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';

const userSchema = new mongoose.Schema({
  firstName: {
    type: String,
    required: function () {
      return this.role !== 'admin';
    }
  },
  lastName: {
    type: String,
    required: function () {
      return this.role !== 'admin';
    }
  },
  email: {
    type: String,
    required: function () {
      return this.role !== 'admin';
    },
    unique: true,
    sparse: true
  },
  username: {
    type: String,
    unique: true,
    sparse: true
  },
  password: {
    type: String,
    required: true
  },
  role: {
    type: String,
    enum: ['admin', 'coordinator', 'faculty', 'student'],
    required: true
  },
  department: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Department',
    required: function () {
      return this.role === 'coordinator' || this.role === 'faculty' || this.role === 'student';
    }
  },
  isApproved: {
    type: Boolean,
    default: function () {
      return this.role === 'admin';
    }
  },
  phoneNumber: String,
  designation: String,
  enrollmentNumber: String,
  address: String,
  photo: String,
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

// Hash password before saving
userSchema.pre('save', async function (next) {
  if (!this.isModified('password')) return next();

  try {
    const salt = await bcrypt.genSalt(10);
    this.password = await bcrypt.hash(this.password, salt);
    next();
  } catch (error) {
    next(error);
  }
});

// Method to compare passwords
userSchema.methods.comparePassword = async function (enteredPassword) {
  return await bcrypt.compare(enteredPassword, this.password);
};

export default mongoose.model('User', userSchema);
